name: ecsim
channels:
  - bioconda
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
dependencies:
  - art=3.19.15
  - numpy=1.25.0
  - pandas=2.0.2
  - pbsim2=2.0.1
  - pysam=0.21.0
  - python=3.9.16
  - scipy=1.10.1
  - seqkit=2.6.1
  - setuptools=68.0.0
